### ISSUE TITLE
Create a cool App Launch Screen

### ISSUE THREAD

**Issue by Rift3000** [Flutter-Buddies/U-DO#1]

**Comment by yash-1th** [comment]
I will work on this.

**Comment by Rift3000** [comment]
Hey @yash-1th remember to finish up the Launch Screen

**Comment by yash-1th** [comment]
Hey @Rift3000, hans said that he is okay with current launch screen. Incase you have any ideas(eg: regarding background colour, logo.. ), please mention them here I will work on it .

**Comment by Rift3000** [comment]
If @hanskokx  said so then its ok

**Comment by yash-1th** [comment]
@hanskokx @Rift3000 Close this issue.
